// Paxos Odin Discussions (POD) Registry
// Automatically updated by `paxos-cli pod promote <slug>`

#let pod-documents = (
  (
    number: "0001",
    slug: "pod-process",
    title: "The Paxos Odin Discussion Process",
    state: "committed",
    area: "process",
    category: "Process Memo",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-16",
    summary: "Defines the POD lifecycle, numbering workflow, Typst project layout, registry, and CLI automation for the paxos-odin project.",
    source: "docs/pod/records/0001-pod-process.typ",
    pdf: "pod-0001-pod-process.pdf",
  ),
  (
    number: "0002",
    slug: "paxos-odin-architecture",
    title: "Paxos-Odin: Architecture and Pure State Machine Design",
    state: "committed",
    area: "architecture",
    category: "Architectural Specification",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-16",
    summary: "Specifies the pure state machine Multi-Paxos core in Odin: explicit effect buffers, zero OS allocations, bitset quorums, chunk-based recovery, and reconfigurable log stop signs.",
    source: "docs/pod/records/0002-paxos-odin-architecture.typ",
    pdf: "pod-0002-paxos-odin-architecture.pdf",
  ),
  (
    number: "0003",
    slug: "durability-and-trimming",
    title: "Durability Contracts, Window Reuse, and Trim Anchors",
    state: "committed",
    area: "protocol",
    category: "Protocol Specification",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-16",
    summary: "Formalizes the persist-then-send invariant, runtime durability gate, power-loss barrier classification, sliding window recycling, and trim anchors.",
    source: "docs/pod/records/0003-durability-and-trimming.typ",
    pdf: "pod-0003-durability-and-trimming.pdf",
  ),
  (
    number: "0004",
    slug: "fast-path-leases",
    title: "Title Goes Here",
    state: "discussion",
    area: "engineering",
    category: "Engineering Discussion",
    status: "Open for Discussion",
    created: "2026-09-16",
    updated: "2026-09-16",
    summary: "Draft discussion note",
    source: "docs/pod/records/0004-fast-path-leases.typ",
    pdf: "pod-0004-fast-path-leases.pdf",
  ),
)
