// Paxos Odin Discussions (POD) Registry
// Automatically updated by `paxodin pod promote <slug>`

#let pod-documents = (
  (
    number: "0001",
    slug: "pod-process",
    title: "The Paxos Odin Discussion Process",
    state: "committed",
    area: "process",
    category: "Process Memo",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-17",
    summary: "Defines the POD lifecycle, numbering workflow, Typst project layout, registry, and CLI automation for the paxos-odin project.",
    source: "docs/pod/records/0001-pod-process.typ",
    pdf: "pod-0001-pod-process.pdf",
  ),
  (
    number: "0002",
    slug: "paxos-odin-architecture",
    title: "Paxos-Odin: Architecture and Pure State Machine Design",
    state: "committed",
    area: "architecture",
    category: "Architectural Specification",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-17",
    summary: "Specifies the 0.2.0 core: a deterministic effect machine over a data-oriented Ledger whose columns are Lamport's variables, bitmaps and bit_set_next scans, packed ballots, pointer payloads, the exact Effects capacities, the ten core files, canonical membership lookup, the replicated log, the learner, the error contract, and the verification that exists today.",
    source: "docs/pod/records/0002-paxos-odin-architecture.typ",
    pdf: "pod-0002-paxos-odin-architecture.pdf",
  ),
  (
    number: "0003",
    slug: "durability-and-trimming",
    title: "Durability Contracts, Window Reuse, and Trim Anchors",
    state: "committed",
    area: "protocol",
    category: "Protocol Specification",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-17",
    summary: "Formalizes the persist-then-send rule, the five durable records and their pointer payloads with the journal-copy obligation, the durability gates, the pre-durable rule and its round-zero exception, the memory floor and window reuse rules on the Ledger, hashless trim anchors, and the ledger_apply versus ledger_replay_fold replay contract.",
    source: "docs/pod/records/0003-durability-and-trimming.typ",
    pdf: "pod-0003-durability-and-trimming.pdf",
  ),
  (
    number: "0004",
    slug: "fast-path-leases",
    title: "Fast-Path Leader Leases and Linearizable Read Verification",
    state: "discussion",
    area: "protocol",
    category: "Protocol Extension",
    status: "Open for Discussion",
    created: "2026-09-16",
    updated: "2026-09-17",
    summary: "Unimplemented lease proposal: identifies the clock, quorum, restart and applied-prefix proof obligations; logical ticks and caught-up queries provide no lease authority.",
    source: "docs/pod/records/0004-fast-path-leases.typ",
    pdf: "pod-0004-fast-path-leases.pdf",
  ),
  (
    number: "0005",
    slug: "idiomatic-odin-api-surface",
    title: "The Idiomatic Odin API Surface",
    state: "committed",
    area: "api",
    category: "Design Record",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-17",
    summary: "Records the 0.1.0 and 0.2.0 API decisions: Ada_Case names, receiver-prefixed spellings plus proc-group verbs, Node_Options with rotating_ownership, Effects mirroring Node, Node_Id as u16, the packed Ballot, the Ledger and its proc group, pointer payloads and the Packet idiom, two before-and-after tables, and the rejected alternatives.",
    source: "docs/pod/records/0005-idiomatic-odin-api-surface.typ",
    pdf: "pod-0005-idiomatic-odin-api-surface.pdf",
  ),
  (
    number: "0006",
    slug: "reconfiguration-and-epoch-isolation",
    title: "Reconfiguration and Epoch Isolation",
    state: "committed",
    area: "protocol",
    category: "Protocol Specification",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-17",
    summary: "Specifies stop signs on one slot line over the Ledger, Log_Sealed from pending through decided, pending_stop_sign for crash repair, init_from_stop and continue_at, strictly increasing configuration ids, Log_Envelope and the checked step, how stop signs behave under rotating ownership, the seeded handover scenarios, and the open questions.",
    source: "docs/pod/records/0006-reconfiguration-and-epoch-isolation.typ",
    pdf: "pod-0006-reconfiguration-and-epoch-isolation.pdf",
  ),
  (
    number: "0007",
    slug: "review-findings-and-verification-evidence",
    title: "Review Findings and Verification Evidence",
    state: "committed",
    area: "verification",
    category: "Review Record",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-17",
    summary: "Preserves the five-pass 2026-09-16 review and the 2026-09-17 recovery follow-up: the correctness findings and repairs, Odin design choices, the error contract, verification evidence, host limits, the recorded 0.1.0 benchmark figures, the parity table with paxos-zig 0.7.0, the API and protocol changes, and the third pass: the data-oriented redesign, the ownership safety bug the simulator caught, and the 0.2.0 verification counts.",
    source: "docs/pod/records/0007-review-findings-and-verification-evidence.typ",
    pdf: "pod-0007-review-findings-and-verification-evidence.pdf",
  ),
  (
    number: "0008",
    slug: "safety-argument",
    title: "Safety Argument: Axioms, Lemmas, and Proof Obligations",
    state: "committed",
    area: "safety",
    category: "Design Record",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-17",
    summary: "States the safety argument for the 0.2.0 core as axioms assumed of the host, lemmas about ballots, quorums, and votes, and proof obligations that name the procedures discharging them.",
    source: "docs/pod/records/0008-safety-argument.typ",
    pdf: "pod-0008-safety-argument.pdf",
  ),
  (
    number: "0009",
    slug: "data-oriented-ledger",
    title: "The Data-Oriented Ledger",
    state: "committed",
    area: "design",
    category: "Design Record",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-17",
    summary: "Records the 0.2.0 layout: the per-message copying problem, Lamport's variables as columns with bitmaps and slot tags, the pointer contract, memory formulas per configuration, what the benchmark measures, the power-of-two and u16 constraints, and the rejected alternatives.",
    source: "docs/pod/records/0009-data-oriented-ledger.typ",
    pdf: "pod-0009-data-oriented-ledger.pdf",
  ),
  (
    number: "0010",
    slug: "rotating-slot-ownership",
    title: "Rotating Slot Ownership",
    state: "committed",
    area: "protocol",
    category: "Protocol Specification",
    status: "Committed",
    created: "2026-09-16",
    updated: "2026-09-17",
    summary: "Specifies rotating slot ownership: round-robin slot ownership, the round-zero ballot reserved for each owner, no-op skips, bounded revocations with per-decree promises, and resubmission of revoked suggestions.",
    source: "docs/pod/records/0010-rotating-slot-ownership.typ",
    pdf: "pod-0010-rotating-slot-ownership.pdf",
  ),
  (
    number: "0011",
    slug: "paxodin-python-sdk",
    title: "Paxodin: A Python SDK over the Odin Core",
    state: "committed",
    area: "python",
    category: "SDK Design and Implementation",
    status: "Implemented",
    created: "2026-09-17",
    updated: "2026-09-17",
    summary: "A uv-managed Python 3.12+ package over a retained-batch C ABI: typed Session and Node APIs, durable journal and history, a validating wire codec, platform wheels built from an sdist outside the checkout, and four-path measured evidence. Reconfiguration, ownership, learners and leases are refused by capability bit.",
    source: "docs/pod/records/0011-paxodin-python-sdk.typ",
    pdf: "pod-0011-paxodin-python-sdk.pdf",
  ),
)
